ai:
    platform:
        openai:
            api_key: '%env(OPENAI_API_KEY)%'


    store:
        # Store configuration

        # chromadb:
        #    default:
        #        client: 'client.service.id'
        #        collection: 'my_collection'
